manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: englmaxi
      url-base: https://github.com/englmaxi/
    - name: hanjin
      url-base: http://github.com/hanjin-kim
  projects:
    - name: zmk
      remote: hanjin
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-config
      remote: englmaxi
      revision: master
  self:
    path: config
